### ISSUE TITLE
streamlit 구현을 위한 module.py 생성

### ISSUE THREAD

**Issue by chaeyeon-h** [pladata-encore/DA36-mini3-SkyMood#18]
## 🌈 Success criteria

1. streamlit 구현을 위한 module.py 생성

## 👷 To-do

- [x] app.py에서 사용할 수 있는 함수 생성
  - [x] 학습된 최고 성능의 model 불러오기
  - [x] web에 load된 사진을 model의 평가를 통해 분류
  - [x] 해당 사진이 구름 어떤 클래스에 속하는 지 ( 클래스 이름, 설명, 클래스 대표사진 return )

## 🧶 Review
 굿
