### ISSUE TITLE
사진 수집/정리

### ISSUE THREAD

**Issue by jovytree** [pladata-encore/DA36-mini3-SkyMood#19]
## 🌈 Success criteria

1. 구름데이터셋 폴더에 올바르지 않게 들어가있는 구름 사진 종류별 정리
2. test_img, sample_img 인터넷 서치로 저장 및 공유. sample_img는 이후 streamlit에서 사용자가 사진을 업로드했을 때 해당하는 것으로 예측되는 구름종류를 화면에 띄워줄 대표사진으로 활용된다.

## 👷 To-do

- [ ] 11개 종류별 구름 사진 test_img, sample_img 각각 3개씩 찾아서 정리
- [ ] 구름 데이터셋 11개 폴더 훑어보며 올바르지 않은 사진 제거
- [ ] test_img에 각각 3개씩 더 추가
