### ISSUE TITLE
새로 정리한 구름 이미지로 MobileNet 모델 재구현(증강 X)

### ISSUE THREAD

**Issue by yejinlee99** [pladata-encore/DA36-mini3-SkyMood#25]
## 🌈 Success criteria

1. 기존 훈련에 사용한 구름 이미지 데이터 라벨링이 잘못되었음을 감지.
    -> 새로 라벨 분리한 데이터로 MobileNet을 훈련해보려고한다.

## 👷 To-do

- [x] 새로운 구름 데이터 불러오기 -> 훈련 train/val 데이터로 사용
- [x] 테스트용 구름 데이터 불러오기 -> 테스트 데이터 용
- [x] CloudSequence
- [x] 모델 생성
- [x] 증강 X 모델 훈련
- [x] 평가하기
- [x] 예측하기

## 🧶 Review

![image](https://github.com/user-attachments/assets/27f88512-f441-4c15-a4f7-5fd6d3a0530f)
![image](https://github.com/user-attachments/assets/0d0058c4-9eab-412c-b357-1f9cad83e402)
