### ISSUE TITLE
streamlit 기본 기능 구현

### ISSUE THREAD

**Issue by chaeyeon-h** [pladata-encore/DA36-mini3-SkyMood#32]
## 🌈 Success criteria

1. Streamlit 기본 기능 구현
- module.py
- app.py 

## 👷 To-do

- [x] 가상환경 구축하기
- [x] streamlit 화면에 결과 출력하기 위해 필요한 함수 생성
  - [x] 입력된 사진 저장하고, resize 등의 과정 진행 하는 함수
  - [x] 모델 불러오고 출력을 위해 필요한 class_name, class_explanation 등을 setting 하는 함수 
  - [x] test 결과 (분류결과, accuracy) return 해주는 함수
  - [x] 비슷한 구름 이미지사진 출력하는 함수

## 🧶 Review

- [x] setting() 함수를 전역변수로 선언하는 것이 더 좋을 것 같음 !
