### ISSUE TITLE
EfficientNet model 성능 평가

### ISSUE THREAD

**Issue by chaeyeon-h** [pladata-encore/DA36-mini3-SkyMood#33]
## 🌈 Success criteria

1. 새로 생성한 data set에 대해 EfficientNet model을 훈련시키고 평가하자

## 👷 To-do

- [x] EfficientNet에서 `Graph execution error` 발생 -> 해결해야함
  - [x] 첫번째 이유, 모델의 구조가 잘못됨 ( label 10개 , 마지막 layer의 units를 2로 설정 )
  - [x] 두번째 이유, train_images_path 값을 전달해야하는데, images_path를 전달함 ( 이 과정에서 labels 에 None 값이 들어갔고 , 길이가 달라짐 )
- [x] 새로운 데이터셋 1번 ( 맑은 구름 / 비 구름 ) 에 대해서 이진 분류 수행 efficientnet 전이학습 )
- [x] 새로운 데이터셋 2번 ( St class 제거 & 장애물 많은 구름 이미지 제거 & 잘못 분류된 사진 재분류 ) 에 대해서 10 class 분류 수행 ( efficientnet 전이학습 ) 
-
