### ISSUE TITLE
ppt 제작

### ISSUE THREAD

**Issue by chaeyeon-h** [pladata-encore/DA36-mini3-SkyMood#35]
## 🌈 Success criteria

1. 발표 ppt 제작

## 👷 To-do

- [x] 개발 배경, 데이터 취득 전처리 , 데이터 다운 및 로드 방식
- [x] 성능 평가를 위해 사용한 3개의 모델의 결과 
- [x] 최종 선정 모델 > 선정이유 : 고려한 사항 ( 1. train/val accuracy , 2. test accuracy , 3. 예측 class 편향 여부 )
- [x] 기대효과
- [x] 소감
