### ISSUE TITLE
MobileNet 테스트(증강 전)

### ISSUE THREAD

**Issue by yejinlee99** [pladata-encore/DA36-mini3-SkyMood#6]
## 🌈 Success criteria

1. Cloud 의 train 데이터를 가지고 MobileNet 모델에 학습 후 평가하고 싶습니다.
2. 일단 돌아가는지 보고 싶어서 아직 증강은 안합니다.

## 👷 To-do

- [x] 모델 불러오기
- [x] 데이터 gdown 하기
- [x] 메타 데이터 생성하기
- [x] train / test 데이터 분리하기
- [x] 모델 학습하기
- [x] 모델 평가하기

## 🧶 Review

![Image](https://github.com/user-attachments/assets/eab910e2-759d-4fb8-bda3-ff14b53dd5da)
