### ISSUE TITLE
MobileNet (증강 후) 학습/평가/예측

### ISSUE THREAD

**Issue by yejinlee99** [pladata-encore/DA36-mini3-SkyMood#8]
## 🌈 Success criteria

1. Cloud 의 train 데이터의 수가 적어서 증강 후 저장해서 MobileNet 모델에 학습 후 평가하고 예측까지 하고 싶습니다.

## 👷 To-do

- [x] CloudSequence 생성하기
- [x] cloud-train 데이터 증강 후 cloud_aug 로 저장하기
- [x] aug 메타 데이터 생성하기
- [x] train / val / test  데이터 분리하기
- [x] 모델 학습하기
- [x] 모델 평가하기
- [x] 예측하기

## 🧶 Review

- 모델 훈련 train / val 데이터
![image](https://github.com/user-attachments/assets/df0c3d7b-7afe-431c-8e7d-a40d81b4fb4f)

- test 데이터로 평가
![image](https://github.com/user-attachments/assets/3147cbbc-f500-492f-9d14-8691a49ad6de)

- test 데이터로 예측
![image](https://github.com/user-attachments/assets/5510503e-a02f-494e-a959-0a70ffcfbadc)
