### ISSUE TITLE
[cloud 데이터 증강 , VGG16 model 성능 평가]

### ISSUE THREAD

**Issue by chaeyeon-h** [pladata-encore/DA36-mini3-SkyMood#9]
## 🌈 Success criteria

1.  cloud data에 대해서 데이터 증강 진행
2. VGG16 모델에 해당 데이터 적용해 성능 평가 
3. EfficientNet 모델에 해당 데이터 적용해 성능 평가

## 👷 To-do

- [x] VGG 전이학습을 위한 모델 불러오기
- [x] 데이터 증강하지 않고 모델 테스트하기 -> [epochs 30회 진행 = accuracy : 최대 0.2]
- [x] cloud data에 대해서 증강 진행하기 (Sequence class 활용)
- [x] 증강된 데이터로 VGG16 모델 테스트하기
- [ ] 증강된 데이터로 EfficientNet 모델 테스트 

## 🧶 Review

- EfficientNet model 테스트 하던 중 error 발생

**Comment by chaeyeon-h** [comment]
Feat : [241126] issue 작성
